### ISSUE TITLE
PR config was not in place in production

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#101]
I've experienced issues as described in https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/8

The reason was that setting "atto_pumukitpr | password" had value "ThisIsASecretPasswordChangeMe". I've manually replaced it with the proper value (from the env repo), and then PR started to work.

Perhaps, it's the same issue with wrong settings after Moodle deployment.

**Comment by athird** [comment]
@michzimny I committed the correct password to the env repo last week, it should be fine. Separately, though, I can't test due to what seems to be an SSO cross-origin [problem](https://github.com/up2university/single-sign-on/issues/52#issue-390669628)

**Comment by Alfro** [comment]
Hi @athird 

Like with #125, this should probably be fine now.
