### ISSUE TITLE
Direct Access to Courses by "Country", "Schools" and "Disciplines" on the Learning Platform

### ISSUE THREAD

**Issue by NelsonDiasFCCN** [up2university/docker-moodle#110]
We need to provide to students and teachers an easy access to "courses by Country", Schools" and "disciplines" (Scientific areas) directly from the learning platform landing page.
This information should be accessible inside the "All Courses" button that doesn't work right now.

Please see the screenshot below.
![screenshot 2018-11-30 at 15 06 47](https://user-images.githubusercontent.com/16823022/49298170-9cfe4400-f4b4-11e8-8479-4d96724cd644.png)

**Comment by michzimny** [comment]
This issue might be the same or at least related to #82

**Comment by athird** [comment]
@michzimny The "All Courses" button works now; I'm not sure what the options are with regard to the requested categorisations. I suspect it isn't possible to list by discipline across categories, is it? Perhaps per-school subcategories within pilot country categories might help - either way, I think this is a WP7 decision. :-)

**Comment by michzimny** [comment]
@athird, yes, I think it's already considered done by the category tree managed by particular national pilot coordinators.
