### ISSUE TITLE
Not able to use the same kind h5p exercises in moodle instances

### ISSUE THREAD

**Issue by ivanoterouvigo** [up2university/docker-moodle#117]
Hi everyone!

H5P is a kind of activity which could be used to create interactive activities.
As a plugin of moodle, I have the posibility of create and activity inside moodle.

I have different behaviour in the test moodle instance and in the production instance.
I mean.
At https://learn.test.up2university.eu

I am able to add all this kind of h5p exercises.

![h5p_all_activities_v001](https://user-images.githubusercontent.com/11814769/50086165-7c482500-01fc-11e9-91af-b3690fdd362a.png)

But if I use the production moodle instance.
I mean.
At learn.up2university.eu

I only see two kind of exercises.

![h5p_all_activities_v002](https://user-images.githubusercontent.com/11814769/50086250-b4e7fe80-01fc-11e9-9226-b5fd91d2df2e.png)

I checked this with different roles but the behaviour is the same as I explain before.

Or you have the posibility to upload a h5p exercise made at other place.

**Comment by athird** [comment]
This is a weirdness with H5P: it seems that unless an administrator goes through the H5P options (when adding an H5P activity) and clicks Get, those options aren't available for other users. @msbachler is looking at automating this. In the meantime, I'll do it for the various platforms.

**Comment by msbachler** [comment]
I have written and tested a script that will automatically install all the h5p libraries. I have testing in a separate running Moodle and in a Moodle build using the up2u docker build. It seems to work fine. So I have tentitavely commited the required code changes into docker-moodle. But I have not added a pull request as I feel someone else should test it as well, given that it is quite a big thing it does.

**Comment by andreacorleto** [comment]
I have the same issue of Ivan. H5P in the production moodle instance has not all the content types (only 20 content types) that are available in the test instance (38 content types). For instance, currently Interactive video content is missing, but it is the most important h5p feature and one of the best to be used by teachers. It not depends on roles and privileges (I've tried to add h5p content as manager, course creator and teacher).

**Comment by michzimny** [comment]
@athird, could you please manage to fix the issue in production? It would be either by manual fix or by deploying the current develop branch with Michelle's fix.

**Comment by athird** [comment]
@michzimny It'll have to be by deployment - looking at it manually, it only lists those 20 content types even to an administrator, so I can't add the others by hand.

**Comment by michzimny** [comment]
Ok, so we should probably schedule new deployments to all instances as there are other pull requestes by Michelle that I merged today.

**Comment by athird** [comment]
@michzimny Just sent you an email about it. :-)

**Comment by athird** [comment]
Fixed, those content types weren't compatible with the version of H5P we had installed, it's upgraded now.
