### ISSUE TITLE
Error on publish video via moodle courses

### ISSUE THREAD

**Issue by ivanoterouvigo** [up2university/docker-moodle#125]
Hi everyone!

I was preparing some content with our teacher. But we had some problems with trying publish video.

I will show the case of use.

We accessed to: https://learn.up2university.eu

Here, I created a course shared with a teacher.
I enrolled him and put him as a teacher profile in this course.

I created some videos with personal recorder inside this course.

First I created a video using personal recorder with my account as a manager in moodle ant after that I published in this course.

I realised other people have no way to see my video.
In my point of view this is a problem.
All tools need to follow the same rules of moodle. I mean
If I create a video with for instance personal recorder, other profiles as teachers of the same course need to have access and to see this video.

I show you the error in this image.

![pr_20_12_2018_v002](https://user-images.githubusercontent.com/11814769/50384544-620fba80-06c6-11e9-8106-8479fe76fda0.png)

Thanks in advance

**Comment by athird** [comment]
@ivanoterouvigo Could you test and update us on the current status of this, please?

**Comment by ivanoterouvigo** [comment]
Sorry @athird, I was not able to test this because I had other error before.

Here you are.

![pr_001](https://user-images.githubusercontent.com/11814769/52450213-625efa80-2b3a-11e9-8fbb-d0d1754f6bae.png)

**Comment by athird** [comment]
@rubenrua Could you email me the right credentials to be used for PR on the production instance, please? I think the above error shows that we have the wrong ones?

**Comment by Alfro** [comment]
Hi @athird 
I think the credentials are already correctly configured, as I can open the Atto plugin (Tried on #154)

Could you check it and maybe close the issue?
