### ISSUE TITLE
Web analytics

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#126]
Please add Matomo tracking code to all pages as documented here:
https://wiki.geant.org/display/UP2U/Web+Analytics

**Comment by msbachler** [comment]
I have added the env for adding additional script to the Moodle HEAD tag area. I tested with the script tag for the Analytics, on the above link given, on my test instance at the OU and the env was set correctly in Moodle Site administration / Appearance / Additional HTML 'additionalhtmlhead'. I checked the source code of that webpage and the script tag had been added in the head area. I don't know if the script did anything analytical though. I have pushed the new code up to both respositories.

**Comment by michzimny** [comment]
Is this change already included in the changes recently deployed by Allan? I don't see the tag in the HEAD area of the pedagogy and production instances.

**Comment by msbachler** [comment]
I was not involded in the deployment. So I don't know if this issue was included. All I can tell you is I have made the changes and pushed the files to the repositories 9 days ago.

**Comment by athird** [comment]
No, it wasn't included, sorry - I didn't think to check for open branches, I only looked for mergeable pull requests. My suggestion then is to configure it manually and then raise PRs and merge them so it will be persistified for the next release, what do you think?

**Comment by michzimny** [comment]
It's fine for me. Could you please do it manually for all the instances? Please note there are different codes for the production and for all the other instances.

**Comment by michzimny** [comment]
ping @athird
