### ISSUE TITLE
Unexpected behavior after intalling extension Poddium

### ISSUE THREAD

**Issue by ivanoterouvigo** [up2university/docker-moodle#151]
First time you try to use Poddium you need to install the extensión, as you can see in the next image. (Poddium_000.png)

![Poddium_000](https://user-images.githubusercontent.com/11814769/58756019-381db800-84f0-11e9-937a-a14b8c389cf6.png)

After installing this extensión you are out of the moodle instances. Both production and test instances.

I think the expected behaviour could be:

**Option 1 )** Open new tab in order to install this extension.

or

**Option 2 )** Come back to moodle instance.

**Comment by vgoya** [comment]
Hi Ivan, This is not the right place for this issue. We will never find it here.

Issues related with the Poddium Recorder should be file in this other repo: https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues

Please, move your issues related with Poddium to the right repo. Thank you in advance

Right places for Up2U Issues are listed here: https://wiki.geant.org/display/UP2U/Issue+tracking

**Comment by ivanoterouvigo** [comment]
Hi @vgoya,

I've just move this issue to your repository.
I apologize, I had a missunderstanding.

**Comment by Alfro** [comment]
The issue this duplicates
was closed by us: https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/22

We have improved Poddium to not require an extension, so this issue is obsolete now and can be closed.
