### ISSUE TITLE
Change default configuration of video (From public to hide)

### ISSUE THREAD

**Issue by ivanoterouvigo** [up2university/docker-moodle#153]
When you begin to record yourselft, it is likely you don't want to publish the first demo videos.

So I suggest to change default configuration fo video from public to hide.

At least to ask if you want to made the video public or not after recording it.

**Comment by Alfro** [comment]
This issue is a duplicated of: https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/24
As this issue does not belong in this repo (and the one corresponding to Poddium was closed by use) I think it can be closed.
