### ISSUE TITLE
Do not exist buttoms if I change editor preferences. Buttoms for accessing to EduOER and Poddium services.

### ISSUE THREAD

**Issue by ivanoterouvigo** [up2university/docker-moodle#155]
Hi everyone,

Do not exist buttoms if I change editor preferences. Buttoms for accessing to EduOER and Poddium services.

This happens when I change editor preferences. If I use any editor and this is not the default one, the buttoms for accessing to EduOER and Poddium don't appear.
I show you one image below.

![Poddium_002](https://user-images.githubusercontent.com/11814769/58756433-e3cb0600-84f8-11e9-9292-d1a2d044c297.png)

Regards

**Comment by Alfro** [comment]
Moved to correct repo: https://github.com/teltek/PuMuKIT2-up2u-pr-bundle/issues/26
Closed there. I think it can be closed here as well.
