### ISSUE TITLE
Log-out link redirects to PODDIUM

### ISSUE THREAD

**Issue by Dimitrispant** [up2university/docker-moodle#175]
When a user logs out from the test instance of the Up2U Leanring Platform, he is redirected to the PODDIUM Webpage

**Comment by Callustian** [comment]
Hi @Dimitrispant . I do not experience the problem. Could you send us the steps and the URLs you use? Thanks.

**Comment by Dimitrispant** [comment]
@Callustian Now it works as expected, so the problem is solved in away.

Regarding the steps, these were the steps I have followed:
1. I used the test instance of the Up2U Learning Platform (learn.test.up2university.eu)
2. I registered on the Up2U learning Platform, with a gmail account.
3. When I tried to log out from the platform, by pressing the log-out link from the drop-down menu on the right of the test instance, I was redirected on the PODDIUM Webpage.

If you can not reproduce this issue, maybe we should close it.

**Comment by Callustian** [comment]
Hi @Dimitrispant . Thank you for your reply. Please close the issue.
