### ISSUE TITLE
Can't build: tar (child): moodle-latest.tgz: Cannot read: Is a directory

### ISSUE THREAD

**Issue by mreyk** [up2university/docker-moodle#18]
On branch `develop`, I've tried a fresh installation with:

```
docker-compose build
```

And I've got this error:

```
Step 27/51 : ADD https://download.moodle.org/download.php/direct/stable33/moodle-latest-33.tgz /var/www/moodle-latest.tgz


 ---> Using cache
 ---> b904d6a91c8a
Step 28/51 : RUN cd /var/www; rm -rf /var/www/html; tar zxvf moodle-latest.tgz; mv /var/www/moodle /var/www/html
 ---> Running in 7c1e647a01b2
tar (child): moodle-latest.tgz: Cannot read: Is a directory
tar (child): At beginning of tape, quitting now
tar (child): Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mv: cannot stat '/var/www/moodle': No such file or directory
ERROR: Service 'moodle' failed to build: The command '/bin/sh -c cd /var/www; rm -rf /var/www/html; tar zxvf moodle-latest.tgz; mv /var/www/moodle /var/www/html' returned a non-zero code: 1
```

**Comment by michzimny** [comment]
What version of Docker do you have? I have Docker 17.09 and I don't experience such issue.

Could you try to debug, what do you have in /var/www/moodle-latest.tgz after step 27? Is it a directory path? What's inside?

**Comment by mreyk** [comment]
```
docker -v
Docker version 17.06.0-ce, build 02c1d87
```
Docker containers are not up, so I can't see the content of `/var/www/`.

```
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

docker ps -a
CONTAINER ID        IMAGE                                          COMMAND                  CREATED              STATUS                          PORTS                                                      NAMES
7554707c6dc2        b904d6a91c8a                                   "/bin/sh -c 'cd /v..."   About a minute ago   Exited (1) About a minute ago                                                              loving_einstein
7c1e647a01b2        b904d6a91c8a                                   "/bin/sh -c 'cd /v..."   About an hour ago    Exited (1) About an hour ago                                                               focused_curie
```

And in localhost:

```
ls /var/www/
html
```

**Comment by michzimny** [comment]
Please comment out or remove from moodle/Dockerfile the all lines after "ADD https://... /var/www/moodle-latest.tgz", and then try:
```
docker build -t testing moodle/
docker run -it --rm testing bash
ls -l /var/www/moodle-latest.tgz
```

If it's a directory, then the question is why?

If it's an archive, then why the subsequent command:
`cd /var/www; rm -rf /var/www/html; tar zxvf moodle-latest.tgz`
fails?

**Comment by mreyk** [comment]
It's a directory:

```
root@11182039cb91:/# ls -l /var/www/moodle-latest.tgz
total 4
drwxr-xr-x 49 1005 1005 4096 Nov 30 20:10 moodle
```
It's weird, because I've downloaded the file to local and it's a tgz file. 

I've removed the folder and tried again. Same issue happened. Is it possible that this line:
```
ADD https://download.moodle.org/download.php/direct/stable33/moodle-latest-33.tgz /var/www/moodle-latest.tgz
```
Is downloading and decompressing the file?

**Comment by michzimny** [comment]
ADD command has a function of decompressing, but docs say:
"If <src> is a local tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed."
https://docs.docker.com/engine/reference/builder/#add

So, that file should not be decompressed by ADD as it is downloaded from a remote URL.

@athird, any ideas?

**Comment by michzimny** [comment]
The quick workaround is to replace this ADD line with:
```
RUN wget https://download.moodle.org/download.php/direct/stable33/moodle-latest-33.tgz -O /var/www/moodle-latest.tgz
```

Please do it locally.

AFAIK people don't recommend using ADD, but it is how we've forked the sources from somewhere. We shall think about replacing ADD with COPY/RUN-wget.

**Comment by mreyk** [comment]
That fixes the error. Thank you very much!
