### ISSUE TITLE
Moodle starts on ipv6.

### ISSUE THREAD

**Issue by elinara** [up2university/docker-moodle#22]
Moodle in docker container starts on ipv6 - how to prevent it? Docker we using on Ubuntu 16.04.
Ipv6 on host is disabled.

netstat -tln
------------------------------------------------------------------
tcp6       0      0 :::80                   :::*                    LISTEN
tcp6       0      0 :::443                 :::*                    LISTEN

ifconfig
br-bd06f6a312e0 Link encap:Ethernet  HWaddr 02:42:68:68:c7:73
          inet addr:172.19.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

br-cb525e0ef6ca Link encap:Ethernet  HWaddr 02:42:16:83:0c:bf
          inet addr:172.18.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

docker0   Link encap:Ethernet  HWaddr 02:42:dd:30:b9:7f
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ens160    Link encap:Ethernet  HWaddr 00:50:56:b6:67:45
          inet addr:158.129.0.158  Bcast:158.129.1.255  Mask:255.255.254.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:167977 errors:0 dropped:0 overruns:0 frame:0
          TX packets:23549 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:143376946 (143.3 MB)  TX bytes:4285569 (4.2 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:160 errors:0 dropped:0 overruns:0 frame:0
          TX packets:160 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:11840 (11.8 KB)  TX bytes:11840 (11.8 KB)

virbr0    Link encap:Ethernet  HWaddr 52:54:00:c4:23:ab
          inet addr:192.168.122.1  Bcast:192.168.122.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by michzimny** [comment]
I think it's rather Docker thing than an issue of this Moodle.

https://docs.docker.com/engine/userguide/networking/default_network/ipv6/
