### ISSUE TITLE
The main authentication backend suggested

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#24]
Now, it's hard to reach the "Login via SAML2" button. Shoudn't we provide it at the front page, instead of the username and password fields for local Moodle authentication? Users should not try to fill up those fields, but rather go to SSO.

**Comment by foobarable** [comment]
Hi, I configured it like this already in the test instance. Its one simple configuration issue.

**Comment by michzimny** [comment]
Thanks, it seems that it's ok now.

**Comment by foobarable** [comment]
(I can't configure it in the production instance since I don't think i have access there)
