### ISSUE TITLE
Enable cron

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#29]
We should enable cron to have the logstore_xapi plugin (and probably other things) working properly. Is it to be done manually on each instance?

**Comment by athird** [comment]
I think we can create and enable cron jobs in the Dockerfile or entrypoint script, wouldn't that be OK?

**Comment by michzimny** [comment]
Sure, it would be good.

**Comment by athird** [comment]
@michzimny I *think* that if you know what the appropriate cron job definition is, and add it to moodle/crontab in the branch 'enable_cron' (https://github.com/up2university/docker-moodle/tree/enable_cron), it *should* then start appropriately.

**Comment by michzimny** [comment]
Shouldn't we just put there something like "php /var/www/html/admin/cli/cron.php" to simply run all Moodle cron jobs?

**Comment by athird** [comment]
Good idea. Daily?

**Comment by athird** [comment]
@michzimny Latest commit should work, I think, to run the Moodle cron tasks

**Comment by michzimny** [comment]
Thanks!
