### ISSUE TITLE
Problems with surname after log in via SSO in production

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#36]
I've authenticated to https://learn.up2university.eu/ via SSO for the first time. My surname is missing although it's rather set in Google:
![missing-surname](https://user-images.githubusercontent.com/1483196/36304668-c310df94-1310-11e8-98bc-05add70dbf76.PNG)

**Comment by michzimny** [comment]
But when I log in via eduGAIN I have even to much data in the surname field:
![extra-surname](https://user-images.githubusercontent.com/1483196/36305645-b712a3d6-1314-11e8-99d3-9f05df034bc2.PNG)

**Comment by athird** [comment]
How does it look now? It was set with common name to be set for the surname field instead of surname, I've updated it in the configuration.

**Comment by michzimny** [comment]
It's ok now, thanks!
