### ISSUE TITLE
The uploaded file exceeds the upload_max_filesize directive in php.ini

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#49]
I get this message when I try to upload a 3MB-large file. It seems that the limit it too low.

Could we have this setting as an environmental variable?

**Comment by athird** [comment]
Where are you uploading a file to, and what for? I *think* that that limit only applies to files going to Moodle's internal storage, which we should only really be using for, e.g., branding images, etc.

**Comment by michzimny** [comment]
I'm uploading either to "Private files" or via the file picker when adding content to a course. Let's assume I'm a teacher and want to create a course using my local files.

It would be ok for me if the Moodle's internal storage is not used by teachers and other users. But how to ensure this way?

Please also have a look at that thread: https://trello.com/c/dwjSbrFn

**Comment by michzimny** [comment]
It still seems to be an issue to be solved, as we don't force people to upload file to backend services.

**Comment by michzimny** [comment]
We need a conclusion here. To allow uploading larger files directly to Moodle, or to force people (or suggest, at least) to upload files to backend services.

The most recent approach expressed in Trello and in mails is for larger files directly to Moodle. @athird, your comment would be needed.

**Comment by michzimny** [comment]
@athird has tried to fix it up, but AFAIK we do not have it persistified yet, right?

**Comment by Tabbasum** [comment]
Should be fixed in PR #87

**Comment by michzimny** [comment]
I've deployed an updated version to the pedagogy instance. It seems it works now, thanks!
