### ISSUE TITLE
Category auto enrol - a missing button to course creation

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#51]
At https://learn-dev.test.up2university.eu/, I enrolled to teacher_course_A as a non-admin user. I'm able to build and visit an URL to the creation form of a new course. However, I cannot find any button that brings me to course creation.

Am I missing something?

Is any action of the admin needed to have the button for regular users?

Being an admin, I can see the large button in the home page (as below), but I don't have it as a non-admin, course creator user. 
![screenshot-2018-3-2 up2university](https://user-images.githubusercontent.com/1483196/36912104-ff653608-1e45-11e8-88f7-2a152387cdc0.png)

**Comment by nadavkav** [comment]
Hi Michal,
You are probably right about "I cannot find any button that brings me to course creation.", as I was not thinking about this from a pov of a non experienced user, and was expecting the users to go to the category of the school and find the "create course" button.
I will update the plugin with a new feature, that display the button inside the block and also a link to the category. and hope it will make life easier for the teachers.
Also, hope that this is what you meant, if not... please clarify the issue

**Comment by michzimny** [comment]
I think the button would make life easier.

However, how to reach course creation by going to the category of the school? The only way I found seems to be quite complex.

**Comment by nadavkav** [comment]
I uploaded a PR: https://github.com/up2university/docker-moodle/pull/54

**Comment by michzimny** [comment]
Thanks.
