### ISSUE TITLE
Language-related PR made deployments interactive

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#57]
https://github.com/up2university/docker-moodle/blob/b231f6e770ddf891b52862dd1440d7c1ad8012ad/moodle/config/moosh-moodle.sh#L13
Unzipping language packs asks questions interactively:
```
replace el/access.php? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
```

**Comment by athird** [comment]
That's really weird, the "-u" flag stopped that happening locally. Anyway, I've just pushed a fix to the languages branch and I'll raise a PR for it now.

**Comment by michzimny** [comment]
Different versions of unzip maybe?

**Comment by athird** [comment]
Could be, but inside Docker, it should always be the same version. The
latest commit should just bypass the issue anyway.

**Comment by michzimny** [comment]
It works.
