### ISSUE TITLE
Editor (atto) toolbar is empty in test enviroment

### ISSUE THREAD

**Issue by rubenrua** [up2university/docker-moodle#61]
Description:
-----------

The editor toolbar is empty in the test environment (https://learn.test.up2university.eu) since the last environment update the bar is empty. The editor used in moodle is the Atto editor and its toolbar is configurable.

Steps to Reproduce
-----------------

1.-  Edit an element with rich text, like a page or a link; or add a new element with rich text.

https://learn.test.up2university.eu/course/modedit.php?update=13&return=0&sr=0

2.- The editor toolbar is empty:

![screen shot 2018-03-08 at 21 56 24](https://user-images.githubusercontent.com/195745/37176516-e1355dbc-231c-11e8-9aa2-b3dcab01258b.png)

Expected Result
--------------

The current editor toolbar, that is like:

![image](https://user-images.githubusercontent.com/195745/37176697-66eb6a14-231d-11e8-8bf5-acbf1040ab59.png)

Technical info:
------------

The current value of  the editor toolbar configuration (`s_editor_atto_toolbar`) in [ / Plugins / Text editors / Atto HTML editor ](https://learn.test.up2university.eu/admin/category.php?category=editoratto) has not new line character (`\n`):

```
collapse = collapse,style1 = title, bold, italic,list = unorderedlist, orderedlist,links = link,files = image, media, managefiles, pumukit, pumukitpr,style2 = underline, strike, subscript, superscript,align = align,indent = indent,insert = equation, charmap, table, clear,undo = undo,accessibility = accessibilitychecker, accessibilityhelper
```

The value must be:
```
collapse = collapse
style1 = title, bold, italic
list = unorderedlist, orderedlist
links = link
files = image, media, managefiles, pumukit, pumukitpr
style2 = underline, strike, subscript, superscript
align = align
indent = indent
insert = equation, charmap, table, clear
undo = undo
accessibility = accessibilitychecker, accessibilityhelper
other=html
```

More info see the default value or  the [Moodle documentation](https://docs.moodle.org/33/en/Text_editor#Toolbar_config_table).

**Comment by athird** [comment]
OK, I've just committed fixes for this to the env and moodle repositories, it works locally now.
