### ISSUE TITLE
Error: Every FilePicker window has the eduOER logo in the corner.

### ISSUE THREAD

**Issue by rubenrua** [up2university/docker-moodle#65]
Every FilePicker window has the eduOER logo in the corner. This should either be deleted (not shown) or changed to the particular service logo (eduOER, CERNbox, DSpace, Personal Recorder)

**Comment by rubenrua** [comment]
![logo_oer_moodle](https://user-images.githubusercontent.com/195745/37413012-5b896ee0-27a6-11e8-9ea9-54ea922dc4df.png)


My fault. I will do a new pull request to fix it.

**Comment by rubenrua** [comment]
To fix this issue quickly, I removed the eduOER logo in the pull request #66

In a future pull request I will add the logo only in the "Add eduOER video" modal.

**Comment by michzimny** [comment]
@rubenrua, is the issue yet to be solved?

**Comment by rubenrua** [comment]
yes. Checked on `learn.test`

![image](https://user-images.githubusercontent.com/195745/38874593-c4c8bbb4-4258-11e8-832a-6a814a171955.png)
