### ISSUE TITLE
Quote mark issue on deployment

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#91]
When deploying to production (`./deploy.sh production 49c2b66d6d1e34c3c3f0bedf888098ef075eb0c6`), the script ends up with the following output:
```
(...)
File uploaded successfully!
/
Configuring mysql container...
envs/pumukit.env: line 8: ": command not found
Done
```

I don't know if that matters but maybe something gets improperly configured. Maybe there's an issue with the quote marks in *.env files? I don't now which approach to quote marks is the right one as we have various of them in the env repo :-)

**Comment by Alfro** [comment]
Hi @michzimny, if you need help with setting these variables maybe we can also give a hand.

**Comment by michzimny** [comment]
Hi @Alfro, you're right that it might be the case with having right values of the config variables. I would prefer though that @athird or @Tabbasum take this and check the values with you if needed.

**Comment by michzimny** [comment]
I'm not experiencing this issue anymore. I think it could have been caused by #92.
