### ISSUE TITLE
Inaccessible admin pages in production

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#92]
Accessing https://learn.up2university.eu/admin/ ends up with a blank page with error: 
> Exception - syntax error, unexpected ';'

Maybe something wrong with values from env repo (I made a deploy an hour ago)?
Maybe it's related to #91

**Comment by athird** [comment]
I just did, effectively, docker-compose down and then docker-compose up, and I can now see the admin pages on production - are they visible to you now?

I can't really see why anything would have changed, though.....

**Comment by michzimny** [comment]
Well, yeah, it's weird. Accessing /admin brings me now to https://learn.up2university.eu/admin/upgradesettings.php and asks for some interactive configuration. Should we proceed? Maybe the config (env) files were not properly processed?

**Comment by athird** [comment]
Oh, strange! I'll try reconfiguring it (we shouldn't fill in the forms manually) - maybe being "unconfigured" is what fixed it? i.e., will it break if I configure it again?

**Comment by athird** [comment]
Looks like it does break it again.

**Comment by michzimny** [comment]
The difference between the production instance and other instances is in the values of env variables. So I think we have some broken values in the production values. What do you think?

**Comment by athird** [comment]
I've located it, I'll send you an email rather than put the fix here. :-D

**Comment by michzimny** [comment]
I've properly escaped the special character in env vars as suggested. It works now. Thanks.
