### ISSUE TITLE
Invalid Consumer Key Debug Error on SeLCont LTI on production instance

### ISSUE THREAD

**Issue by Dimitrispant** [up2university/docker-moodle#94]
Here is how the error goes:

1. I select SeLCont LTI external tool on the production instance for a course I created.
2. When I set it up and try to open the SeLCont instance I have a debug message on the URL like this "Invalid Consumer Key"

I think that this error may be from a missing variable from the .env template of SeLCont (e.g. SELCONT_CONSUMER ?) or it may need a way to force SSL for this external tool (or may both cause this problem).

What do you think @athird ? 

![image](https://user-images.githubusercontent.com/13375110/46734432-d75d1900-cc9b-11e8-8bb7-e58a9a141e7e.png)

**Comment by athird** [comment]
The .env files (and the template) for SeLCont for both production and pedagogy instances seem to have the same variables in them. The only possibly significant differences I can see between them are for the SELCONT_KEY_URL variable. Neither of them specify HTTPS, and the pedagogy one has a URL ending in "/selcont-key" where the production one just ends in "/selcont". Could either of those make a difference?

**Comment by michzimny** [comment]
@athird, are you watching the latest version of env repo? My HEAD is 51835d9a6e64d01abfbe383e9a8eb014b4871910 and I see more differences between the instances:

```
s$ diff dev/selcont.env production/selcont.env
2c2
< SELCONT_PASSWORD='d.......'
---
> SELCONT_PASSWORD='v.......'
4,5c4,5
< SELCONT_KEY_URL='http://selcont.test.up2university.eu/selcont-key'
< SELCONT_URL='selcont.test.up2university.eu'
---
> SELCONT_KEY_URL='http://selcont.up2university.eu/selcont'
> SELCONT_URL='selcont.up2university.eu'

```

**Comment by Dimitrispant** [comment]
@athird The URL ending is the the consumer key that is used on each instance. However when you create an LTI external tool manually, it also asks for the consumer key on a separate field and you have also to check the option to force SSL. However, I'm not sure how these options can be adapted on the .env template.

**Comment by athird** [comment]
@Dimitrispant Any update on this?

**Comment by michzimny** [comment]
The update we have from @Dimitrispant from 6th Nov is the following (but these are my words):
The integration Moodle-SeLCont does not work properly after Moodle is deployed but the workaround is to simply put the configuration manually into the admin panel (or just open and save existing configuration forms). 

So, it seems to be related to similiar issue with CERNBox configuration after deployment.

**Comment by athird** [comment]
@Dimitrispant How is it behaving now? In theory, if it was related to the CERNBox configuration after deployment issue, #90, then it *ought* to be fixed now. Could you check and let me know, please, so that we can close this issue, if fixed, or look into it further, if not?

**Comment by Dimitrispant** [comment]
@athird It works like a charm. If I have any other issues I will contact you.

**Comment by athird** [comment]
@Dimitrispant Great, thanks!
